box::use(
  dplyr[case_when],
  stringr[str_ends],
  shiny[updateTextInput, updateSelectInput, updateSelectizeInput, updateNumericInput],
)

# Description
#
# This script contains functions to update data with patient files
# generated by Bestdose or Tucuxi (not available at the moment).
# The update_data function identifies the source software from the file
# extension, and return the subfunctions to be used in Shiny app
# The update_patient_data.mb2 and update_tdm_history.mb2 functions update data
# for Bestdose datafiles
# The update_patient_data.tucuxi and update_tdm_history.tucuxi functions will
# update data for Tucuxi datafiles


#' @title update_data

#' @description
#' update_data purpose is to identify the file extension and call the right subfunctions
#' to update shiny data from file
#'
#' @param file_path correspond to the file location
#' 
#' @export

update_data <- function(file_path) {
  extension <- case_when(
    str_ends(file_path, pattern = ".mb2") ~ "bestdose",
    TRUE ~ "unknown"
  )

  update_patient_data <- switch(extension,
    "bestdose" = update_patient_data.mb2
  )

  update_tdm_history <- switch(extension,
    "bestdose" = update_tdm_history.mb2
  )

  return(list(
    "update_patient_data" = update_patient_data,
    "update_tdm_history" = update_tdm_history
  ))
}


#' @title update_patient_data.mb2
#' @description function created to update all dynamic fields in the app
#' @param input is a list generated with read_file.mb2 / read_file
#' @param session correspond to the session used by the shiny app
#' 
#' @export 
#' 
update_patient_data.mb2 <- function(input, session) {
  weight_df <- input[["weight_df"]]
  birthdate <- format(as.Date(input[["birthdate"]]), "%Y-%m-%d")

  # Update input fields with loaded data
  updateTextInput(session, "last_name", value = input[["patient_last_name"]])
  updateTextInput(session, "first_name", value = input[["patient_first_name"]])
  updateTextInput(session, "ward", value = input[["ward"]])
  #updateTextInput(session, "room", value = input[["room"]])
  updateTextInput(session, "birthdate", value = as.Date(birthdate)) # not yet supported

  # update select Input
  updateSelectInput(session, "sex", selected = input[["sex"]])
  updateSelectInput(session, "drug", selected = input[["drug_name"]])
  updateSelectizeInput(session, "hospital",
    selected = input[["hospital"]],
    choices = c(labels("hospital", "choices", lang), input[["hospital"]])
  )

  # update numeric
  updateNumericInput(session, "height", value = input[["height"]])
  updateNumericInput(session, "weight", value = weight_df[nrow(weight_df), 2])
}

# update the dataframe
#' @title update_tdm_history.mb2
#' @description function created to read and get all the dosing and serum
#' level information in the .mb2 file
#' @param input is a list generated with read_file.mb2 / read_file
#'
#' @export
update_tdm_history.mb2 <- function(input) {
  return(list(
    "dose_df" = input[["dose_df"]],
    "level_df" = input[["level_df"]],
    "weight_df" = input[["weight_df"]]
  ))
}
