# Description
#
# This script contains functions to open and extract data from patient files
# generated by Bestdose or Tucuxi (not available at the moment).
# The read_file function identifies the source software from the file extension
# The read_file.mb2 function extracts data from Bestdose datafiles
# The read_file.tucuxi function will extract data from Tucuxi datafiles


#' @title read_file
#' @description
#' read_file purpose is to identify the file extension and call the right subfunctions
#' to open and extract data from file
#'
#' @param file_path correspond to the file location
#' 
#' @export 

read_file <- function(file_path) {
  extension <- dplyr::case_when(
    stringr::str_ends(file_path, pattern = ".mb2") ~ "bestdose",
    TRUE ~ "unknown"
  )
  read_function <- switch(extension, "bestdose" = read_file.mb2)

  data_file <- read_function(file_path)
  return(data_file)
}

#' @title read_file.mb2
#' @description
#' read_file.mb2 purpose is to get .mb2 file (PastrX file for BestDose (R)) and
#' extract all the useful information contained in the file
#'
#' @param file_path correspond to the file location
#' 
#' @export

read_file.mb2 <- function(file_path) {
  # Read lines from the file
  lines <- readLines(file_path)

  # Create an empty dataframe to store the weight history
  weight_df <- data.frame(
    Weight_date = character(),
    Weight_value = numeric()
  )

  # create empty df to store the dosing history
  dose_df <-
    data.frame(
      Admin_date = as.character(),
      Route = as.character(),
      Infusion_rate = as.numeric(),
      Infusion_duration = as.numeric(),
      Dose = as.numeric(),
      Creatinin_Clearance = as.numeric()
    )

  # create empty df to store the level history
  level_df <- data.frame(
    tdm_time = as.character(),
    Concentration = as.numeric()
  )

  # Variable mandatory to adapt file based on the different number of inputs (weight, dose, level)
  parts <- strsplit(lines[6], "\\s+")[[1]]
  weight_number <- as.numeric(parts[2])

  parts <- strsplit(lines[16 + weight_number], "\\s+")[[1]]
  dose_number <- as.numeric(parts[3])
  level_number <- as.numeric(parts[4])

  # compute file total length
  file_length <- 22 + dose_number + level_number + weight_number

  # extract all necessary variables
  parts <- strsplit(lines[3], "\\s+")[[1]]
  patient_last_name <- stringr::str_sub(lines[3], 1, 20) |> stringr::str_squish()
  patient_first_name <- stringr::str_sub(lines[3], 20, 32) |> stringr::str_squish()
  sex_extract <- stringr::str_sub(lines[3], 33, 33)
  sex <- ifelse(sex_extract == "F", "Female", "Male")

  # Extract patient hospital, Height and birth-date (line 4)
  # NOTE : in PastrX file, the 4th lines always contain the hospital (first 10)
  # characters), the ward (char 10 - 20), the room (char 21 - 27).
  parts <- strsplit(lines[4], "\\s+")[[1]]
  height <- paste(parts[length(parts) - 5]) # will always return the height as it is always the sixth element from the end
  birthdate <- paste(parts[length(parts) - 3]) # will always return birth-date as it is always the fourth element from the end

  # get the hospital name
  get_hospital_name <- strsplit(substr(lines[4], start = 1, stop = 10), "\\s+")[[1]]
  hospital <- ifelse(length(get_hospital_name) > 1, paste(get_hospital_name[1], get_hospital_name[2]), get_hospital_name)

  # get ward the patient is in
  get_ward <- substr(lines[4], start = 11, stop = 20)
  ward <- ifelse(length(get_ward) > 1, paste(get_ward[1], get_ward[2]), get_ward) |>
    stringr::str_squish() # removes whitespace from start and end of string

  # get the room the patient is in
  get_room <- substr(lines[4], start = 21, stop = 27)
  room <- ifelse(length(get_room) > 1, paste(get_room[1], get_room[2]), get_room) |>
    stringr::str_squish() # removes whitespace from start and end of string


  # Extract weight value
  if (weight_number != 0) {
    for (i in 1:weight_number) {
      parts <- strsplit(lines[9 + i], "\\s+")[[1]] # get the position of serum level value relative to the rest of the df
      weight_df[i, 1] <- paste(parts[1:2], collapse = " ")
      weight_df[i, 2] <- as.numeric(parts[3])
    }
  }

  # Extract Drug and number of dose/concentrations
  parts <- strsplit(lines[16 + weight_number], "\\s+")[[1]]
  drug_name <- parts[1]

  # Extract the number of dose given
  if (dose_number != 0) {
    for (i in 1:dose_number) {
      parts <- strsplit(lines[19 + weight_number + i], "\\s+")[[1]] # get the position of dose relative to the rest of the df
      dose_df[i, 1] <- paste(parts[1:2], collapse = " ")
      dose_df[i, 2] <- parts[3]
      dose_df[i, 3] <- as.numeric(parts[4])
      dose_df[i, 4] <- as.numeric(parts[5])
      dose_df[i, 5] <- as.numeric(parts[6])
      dose_df[i, 6] <- as.numeric(parts[7])
    }
  }
  # Extract drug level
  if (level_number != 0) {
    for (i in 1:level_number) {
      parts <- strsplit(lines[21 + weight_number + dose_number + i], "\\s+")[[1]] # get the position of serum level value relative to the rest of the df
      level_df[i, 1] <- paste(parts[1:2], collapse = " ")
      level_df[i, 2] <- as.numeric(parts[3])
    }
  }
  return(list(
    "hospital" = hospital,
    "patient_first_name" = patient_first_name,
    "patient_last_name" = patient_last_name,
    "ward" = ward,
    "room" = room,
    "height" = height,
    "weight_df" = weight_df,
    "birthdate" = birthdate,
    "drug_name" = drug_name,
    "sex" = sex,
    "level_number" = level_number,
    "dose_df" = dose_df,
    "level_df" = level_df
  ))
}
